
#include "StandardKeyboardEvents.h"

#include "../Lua/LuaEnvironment.h"

namespace PE {
namespace Events {

	PE_IMPLEMENT_CLASS1(Event_KEY_A_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_S_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_D_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_W_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_PERIOD_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_COMMA_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_K_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_L_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_M_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_G_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_P_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_O_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_C_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_Z_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_LEFT_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_DOWN_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_RIGHT_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_UP_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_MOUSE_LBUTTON_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_MOUSE_ROTATE, Event);
	PE_IMPLEMENT_CLASS1(Event_SPACEBAR_HELD, Event);
};
};
